name = "ws-relay"
main = "src/index.js"
compatibility_date = "2022-05-18"

[durable_objects]
bindings = [
    { name = "RELAY", class_name = "Relay7" } # Binding to our DurableObjectExample class
]



[[migrations]]
tag = "v6" # Should be unique for each entry
deleted_classes = ["Relay5"] # Array of deleted class names
new_classes = ["Relay6"]

[[migrations]]
tag = "v7" # Should be unique for each entry
deleted_classes = ["Relay6"] # Array of deleted class names
new_classes = ["Relay7"]