name = "ws-relay"
main = "src/index.js"
compatibility_date = "2022-05-18"

[durable_objects]
bindings = [
    { name = "RELAY", class_name = "Relay10" } # Binding to our DurableObjectExample class
]




[[migrations]]
tag = "v7" # Should be unique for each entry
deleted_classes = ["Relay8"] # Array of deleted class names
new_classes = ["Relay9"]

[[migrations]]
tag = "v10" # Should be unique for each entry
deleted_classes = ["Relay8"] # Array of deleted class names
new_classes = ["Relay10"]